### ISSUE TITLE
Readme has outdated information about where to get dxil.dll

### ISSUE THREAD

**Issue by Elabajaba** [Traverse-Research/hassle-rs#54]
The downloads on the release tab of https://github.com/Microsoft/DirectXShaderCompiler seem to now include a more up to date version of dxil.dll than what WindowsSDK includes.

![image](https://user-images.githubusercontent.com/177631/212014292-f46ba97e-8ed0-45c4-89f5-d0a81422e854.png)

(left: SDK, right: latest github release (from releases, not CI)

**Comment by MarijnS95** [comment]
PR welcome! That said, is there any noticeable bugfix or feature provided by the new DLL?

**Comment by Jasper-Bekkers** [comment]
Updated the readme to point to https://github.com/microsoft/DirectXShaderCompiler/releases/latest

**Comment by Elabajaba** [comment]
> PR welcome! That said, is there any noticeable bugfix or feature provided by the new DLL?

Not that I know of, but at least previously it would fail to validate valid shaders if you used a dxil.dll that was too old and/or used features that were too new.

It also just simplifies getting the dlls (and the instructions for wpgu users for switching to dxc) to be able to just download it from one spot.
