### ISSUE TITLE
Automatic validation fails if `dxil.dll` isn't in the local folder. 

### ISSUE THREAD

**Issue by Elabajaba** [Traverse-Research/hassle-rs#60]
Someone ran into this with wgpu (https://github.com/gfx-rs/wgpu/issues/3433), and it turns out if you're pointing to dxil.dll outside of the local scope it'll silently fail to validate the shaders.

The solution seems to be passing `-Vd` in the compile flags and doing explicit validation.

Is it better to always do explicit validation, or should I avoid passing -Vd unless the user has set a custom `dxil.dll` path?

**Comment by MarijnS95** [comment]
I think we ignore validation and always call https://github.com/Traverse-Research/hassle-rs/blob/104a44ae93ef0ee5f4962b73e912d1d9d6663707/src/fake_sign/mod.rs#L41. Doesn't [`validate_dxil()`](https://github.com/Traverse-Research/hassle-rs/blob/104a44ae93ef0ee5f4962b73e912d1d9d6663707/src/utils.rs#L159) fail when the binary cannot be found?

**Comment by Elabajaba** [comment]
I was calling `dxc_compiler.compile(...)`, which will automatically validate the shaders, so I wasn't explicitly validating them afterwards. Wgpu is currently only targeting Windows for its dx12 backend, so we're not using fake_sign.

**Comment by MarijnS95** [comment]
Fwiw if this is an issue internal to `dxcompiler.dll`, create it over at their repository :)

**Comment by Elabajaba** [comment]
Yeah, just good to also document it here in case anyone else runs into it.
